name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build text-labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - name: Setup GO
        uses: actions/setup-go@v5
      - name: Build Next.js
        run: yarn && yarn build && yarn export
      - name: Build app
        run: |
          cd app
          cp -rf ../out .
          GOOS=linux GOARCH=amd64 go build -o dist/asr-label-linux-x64 main.go
          GOOS=windows GOARCH=amd64 go build -o dist/asr-label-win-x64.exe main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/asr-label-macos-x64 main.go
          GOOS=darwin GOARCH=arm64 go build -o dist/asr-label-macos-arm64 main.go

      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: asr-label-linux-x64.zip
          path: app/dist/asr-label-linux-x64

      - name: Upload macos artifact
        uses: actions/upload-artifact@v4
        with:
          name: asr-label-macos-x64.zip
          path: app/dist/asr-label-macos-x64

      - name: Upload macos arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: asr-label-macos-arm64.zip
          path: app/dist/asr-label-macos-arm64

      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: asr-label-win-x64.zip
          path: app/dist/asr-label-win-x64.exe
